CREATE TABLE country_master
(
	COUNTRY_PK number(10,0) NOT NULL,
	NAME varchar2(50 char) NOT NULL UNIQUE,
	COUNTRY_ABBR varchar2(5 char),
	STATUS varchar2(1) NOT NULL,
	DELETED varchar2(1) NOT NULL,
	CREATED_BY varchar2(20) NOT NULL,
	CREATED_TIMESTAMP timestamp NOT NULL,
	UPDATED_BY varchar2(20),
	UPDATED_TIMESTAMP timestamp,
	PRIMARY KEY (COUNTRY_PK)
);

CREATE TABLE state
(
	STATE_PK number(10,0) NOT NULL,
	FK_COUNTRY number(10,0) NOT NULL,
	NAME varchar2(30 char) NOT NULL,
	STATUS varchar2(1) NOT NULL,
	DELETED varchar2(1) NOT NULL,
	CREATED_BY varchar2(10) NOT NULL,
	CREATED_TIMESTAMP timestamp NOT NULL,
	UPDATED_BY varchar2(10),
	UPDATED_TIMESTAMP timestamp,
	STATE_CODE VARCHAR2(2),
	PRIMARY KEY (STATE_PK)
);

ALTER TABLE state
	ADD CONSTRAINT FK_COUNTRY_STATE FOREIGN KEY (FK_COUNTRY)
	REFERENCES country_master (COUNTRY_PK)
;

CREATE INDEX IDX_STATE_FK_COUNTRY ON state  (FK_COUNTRY);

CREATE SEQUENCE COUNTRY_SEQ 
INCREMENT BY 1 
START WITH 1 
MAXVALUE 9999999
MINVALUE 1 
NOCACHE;

CREATE SEQUENCE STATE_SEQ 
INCREMENT BY 1 
START WITH 1 
MAXVALUE 9999999
MINVALUE 1 
NOCACHE;

