--liquibase formatted sql

CREATE TABLE TEST1
(
	TEST_PK NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(20),
	ID NUMBER(10),
	STATUS VARCHAR2(1),
	CREATED_TIMESTAMP TIMESTAMP,
	CREATED_BY VARCHAR2(10)
);
--rollback drop table test1;

ALTER TABLE TEST1 ADD DELETED VARCHAR2(1);
--rollback drop table test1;